/*
 * Copyright © 2025 Gage Singleton <singletongage948@gmail.com>	
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define MAX_SHELLCODE_SIZE 4096

// Convert a hex digit to integer value
static int hexval(int c) {
    if ('0'<=c && c<='9') return c-'0';
    if ('a'<=c && c<='f') return c-'a'+10;
    if ('A'<=c && c<='F') return c-'A'+10;
    return -1;
}

int main(void) {
    char line[65536];
    printf("Paste shellcode as one line (supports \\xNN, spaces, commas):\n");
    if (!fgets(line, sizeof(line), stdin)) {
        fprintf(stderr, "No input.\n");
        return 1;
    }

    // Normalize into pure hex digits
    char norm[65536];
    size_t ni = 0;
    for (size_t i=0; line[i] && ni+4 < sizeof(norm); ++i) {
        if (line[i] == '\\' && (line[i+1]=='x' || line[i+1]=='X')
            && isxdigit((unsigned char)line[i+2]) && isxdigit((unsigned char)line[i+3])) {
            norm[ni++] = line[i+2];
            norm[ni++] = line[i+3];
            i += 3;
        } else if (isxdigit((unsigned char)line[i])) {
            norm[ni++] = line[i];
        } else {
            // ignore spaces, commas, etc.
        }
    }
    norm[ni] = '\0';

    if (ni == 0 || (ni % 2) != 0) {
        fprintf(stderr, "Invalid input: must contain even number of hex digits.\n");
        return 1;
    }

    size_t bytecount = ni / 2;
    if (bytecount > MAX_SHELLCODE_SIZE) {
        fprintf(stderr, "Shellcode too large (max %d bytes).\n", MAX_SHELLCODE_SIZE);
        return 1;
    }

    unsigned char bytes[MAX_SHELLCODE_SIZE];
    for (size_t i=0; i<bytecount; ++i) {
        int hi = hexval(norm[2*i]);
        int lo = hexval(norm[2*i+1]);
        if (hi < 0 || lo < 0) {
            fprintf(stderr, "Invalid hex at position %zu.\n", 2*i);
            return 1;
        }
        bytes[i] = (unsigned char)((hi<<4)|lo);
    }

    FILE *out = fopen("loader.c", "w");
    if (!out) { perror("fopen loader.c"); return 1; }

    fprintf(out,
"/*\n"
" * loader.c\n"
" * Generated by Shellcode Loader Generator\n"
" * MIT License\n"
" * WARNING: Only run in a controlled, safe environment.\n"
" * By default, this loader does NOT execute shellcode.\n"
" * Set ENABLE_EXECUTION to 1 to enable execution.\n"
" */\n\n"
"#include <stdio.h>\n"
"#include <stdlib.h>\n"
"#include <string.h>\n"
"#include <sys/mman.h> // Linux; replace with VirtualAlloc for Windows\n\n"
"#define ENABLE_EXECUTION 1\n\n"
"int main(void) {\n"
"    unsigned char shellcode[] = {");

    for (size_t i = 0; i < bytecount; ++i) {
        if (i % 12 == 0) fprintf(out, "\n        ");
        fprintf(out, "0x%02X", bytes[i]);
        if (i + 1 != bytecount) fprintf(out, ", ");
    }

    fprintf(out,
"\n    };\n"
"    size_t sc_size = sizeof(shellcode);\n\n"
"    printf(\"Shellcode (%zu bytes):\\n\", sc_size);\n"
"    for (size_t i = 0; i < sc_size; i++) {\n"
"        printf(\"%02X \", shellcode[i]);\n"
"    }\n"
"    printf(\"\\n\");\n\n"
"#if ENABLE_EXECUTION\n"
"    void* exec_mem = mmap(0, sc_size, PROT_READ | PROT_WRITE | PROT_EXEC,\n"
"                          MAP_ANON | MAP_PRIVATE, -1, 0);\n"
"    if (exec_mem == MAP_FAILED) {\n"
"        perror(\"mmap failed\");\n"
"        return 1;\n"
"    }\n"
"    memcpy(exec_mem, shellcode, sc_size);\n"
"    ((void(*)())exec_mem)();\n"
"#else\n"
"    printf(\"Execution disabled. Set ENABLE_EXECUTION to 1 to run shellcode.\\n\");\n"
"#endif\n"
"    return 0;\n"
"}\n");

    fclose(out);
    printf("Generated loader.c with %zu bytes of shellcode.\n", bytecount);
    printf("Compile with: gcc loader.c -o loader\n");
    return 0;
}
